/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AmorePortal.view;

/**
 *
 * @author Eka
 */
public class PanelPaket extends javax.swing.JPanel {

    int hitungGambar = 0;

    /**
     * Creates new form PanelPaket
     */
    public PanelPaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/nextButton.png"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/previousButton.png"))); // NOI18N
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(gambar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(gambar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousButton)
                    .addComponent(nextButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if (nextButton == evt.getSource() && hitungGambar == 0) {
            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket2.jpg")));
            hitungGambar = hitungGambar + 1;
        } else if (nextButton == evt.getSource() && hitungGambar == 1) {
            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket3.jpg")));
            hitungGambar = hitungGambar + 1;
        } else if (nextButton == evt.getSource() && hitungGambar == 2) {
            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket1.jpg")));
            hitungGambar = 0;
        }

    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
        if (previousButton == evt.getSource() && hitungGambar == 2) {
            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket3.jpg")));
            hitungGambar = hitungGambar - 1;
        } else if (previousButton == evt.getSource() && hitungGambar == 1) {
            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket2.jpg")));
            hitungGambar = hitungGambar - 1;
        } else if (previousButton == evt.getSource() && hitungGambar == 0) {
            gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmorePortal/image/paket1.jpg")));
            hitungGambar = 2;
        }
    }//GEN-LAST:event_previousButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gambar;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
